# Generated by Django 4.2.7 on 2023-12-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='max',
            new_name='penalty',
        ),
    ]
