# Generated by Django 4.2.7 on 2023-12-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_max_customuser_penalty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='penalty',
            new_name='routeKM',
        ),
        migrations.AddField(
            model_name='customuser',
            name='routeName',
            field=models.CharField(blank=True, null=True),
        ),
    ]
