# Generated by Django 4.2.7 on 2023-12-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_transportationrecord_latitudein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationrecord',
            name='latitudeIN',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrecord',
            name='latitudeOUT',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrecord',
            name='longitudeIN',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrecord',
            name='longitudeOUT',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
