# Generated by Django 4.2.7 on 2023-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_transportationrecord_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationrecord',
            name='penalty',
        ),
        migrations.AlterField(
            model_name='transportationrecord',
            name='latitudeIN',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrecord',
            name='latitudeOUT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrecord',
            name='longitudeIN',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrecord',
            name='longitudeOUT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
